[default]

api_prefix = "/api/v1"
log_file = "@format {env[BASE_DIR]}/logs/ost.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"
cors_origins = ["*"]
reload_enable = true
domain = "https://pyfat.sd.di.huc.knaw.nl"

metrics_file = "https://raw.githubusercontent.com/CLARIAH/pyFAT/refs/heads/develop/src/pyfat/resources/metrics/clarin_fip_metrics_v0.3.yaml" # internet file or local
